version: '3'

services:
  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  datascience-notebook:
      image: jupyter/datascience-notebook
      volumes:
        - ./notebook:/home/jovyan/work
      ports:
        - 8888:8888
      container_name:  datascience-notebook-container